---
spring:
  datasource:
    url: jdbc:h2:file:${BAYWATCH_HOME:.}/.baywatch/baywatch
    driver-class-name: org.h2.Driver
    username: baywatch
    password: hasselhoff

server:
  port: ${BAYWATCH_SERVER_PORT:8081}
  error:
    include-message: ALWAYS

# Avoid infinite stacktrace due to reactor
logging:
  exception-conversion-word: "%wEx{full, reactor.core.publisher}"
  level:
    root: INFO
    org.jooq: WARN
    fr.ght1pc9kc.baywatch: DEBUG

baywatch:
  base-route: /api
  security:
    cookie.name: X-TOKEN
    jwt.validity: 1h
  scrapper:
    start: true
    frequency: 1h
