---
spring:
  datasource:
    url: jdbc:h2:file:${BAYWATCH_HOME:.}/.baywatch/baywatch
    driver-class-name: org.h2.Driver
    username: baywatch
    password: hasselhoff

server:
  port: ${BAYWATCH_SERVER_PORT:8081}
  error:
    include-message: ALWAYS

logging:
  # Avoid infinite stacktrace due to reactor
  exception-conversion-word: "%wEx{full, reactor.core.publisher}"
  level:
    root: INFO
    org.jooq: WARN
    fr.ght1pc9kc.baywatch: ${BAYWATCH_LOG_LEVEL:DEBUG}
    fr.ght1pc9kc.scraphead: ${BAYWATCH_LOG_LEVEL:DEBUG}
    # Avoid unwanted log error ...
    org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator: OFF
    reactor.netty.http.client: ERROR

baywatch:
  base-route: /api
  security:
    cookie:
      name: X-TOKEN
      validity: ${BAYWATCH_COOKIE_VALIDITY:24h}
    jwt.validity: ${BAYWATCH_TOKEN_VALIDITY:1h}
  scrapper:
    start: true
    timeout: ${BAYWATCH_SCRAPPER_TIMEOUT:2s}
    frequency: ${BAYWATCH_SCRAPPER_FREQUENCY:1h}
    conservation: ${BAYWATCH_SCRAPPER_CONSERVATION:3m}
    supportedScheme:
      - http
      - https
